# Jekyll Configuration

# Site Settings
url: ""
website_url: "https://s3.amazonaws.com/loklad.com/"
title: Loklad ☕ + ? + ?️
email: 
images-path: /static/images/
videos-path: /static/videos/
js-path: /static/js/
baseurl: "" # the subpath of your site, e.g. /blog